{% set version = "20251206" %}
{% set name = "m4ri" %}

package:
  name: m4ri
  version: {{ version }}

source:
  url: https://github.com/malb/m4ri/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6ee166b8085a6d369708dc7c20e831fe3a680f118717b1b0816d6f2a458c262d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("m4ri") }}

requirements:
  build:
    - libtool                # [unix]
    - automake               # [unix]
    - autoconf               # [unix]
    - make                   # [unix]
    - m4                     # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - autotools_clang_conda  # [win]
  host:
    - libpng
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/m4ri/m4ri.h                             # [unix]
    - test ! -f ${PREFIX}/lib/libm4ri.a                                 # [unix]
    - test -f ${PREFIX}/lib/libm4ri${SHLIB_EXT}                         # [unix]
    - if not exist %LIBRARY_BIN%\\m4ri-1.dll exit 1                     # [win]
    - if not exist %LIBRARY_LIB%\\m4ri.lib exit 1                       # [win]
    - if exist %LIBRARY_LIB%\\m4ri_static.lib exit 1                    # [win]
    - if not exist %LIBRARY_INC%\\m4ri\\m4ri.h exit 1                   # [win]


about:
  home: https://github.com/malb/m4ri
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: M4RI is a library for fast arithmetic with dense matrices over F2
  dev_url: https://github.com/malb/m4ri

extra:
  recipe-maintainers:
    - isuruf
    - marcelotrevisani
    - saraedum
